version: 0.2

phases:
  pre_build:
    commands:
    - echo pre-building...
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
    - echo building...
    - mvn install
  post_build:
    commands:
    - echo post-building...
artifacts:
  files:
  - target/*.jar