version: 0.2

phases:
  pre-build:
    commands:
    - echo pre-building...
  build:
    commands:
    - echo building...
    - mvn install
  post-build:
    commands:
    - echo post-building...
artifacts:
  files:
  - target/*.jar